Repository boostcampwm-2022/web05-SleepyWoods, pull requests merged in 2022-11, with the labels that each got.

#11 [1주차] 백엔드 개발환경 세팅
  backend/.eslintrc.js
  backend/.gitignore
  backend/.prettierrc
  backend/README.md
  backend/nest-cli.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/configs/typeorm.config.ts
  backend/src/main.ts
  backend/tsconfig.build.json
  backend/tsconfig.json
Labels: 백엔드, 세팅

#12 [1주차] 프론트엔드 개발환경 셋팅
  .gitignore
  backend/.gitignore
  frontend/.eslintrc.js
  frontend/.prettierrc
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/global.ts
  frontend/src/main.tsx
  frontend/src/theme.ts
  frontend/src/types/emotion.d.ts
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  package.json
Labels: 프론트엔드, 세팅

#14 main page 구조 세팅
  frontend/package-lock.json
  frontend/package.json
  frontend/src/component/Background/background.styled.ts
  frontend/src/component/Background/index.tsx
  frontend/src/component/Modal/index.tsx
  frontend/src/component/Modal/modal.styled.ts
  frontend/src/component/Oauth/index.tsx
  frontend/src/component/Oauth/oauth.styled.ts
  frontend/src/component/Setting/index.tsx
  frontend/src/component/Setting/setting.styled.ts
  frontend/src/global.ts
  frontend/src/page/Main/index.tsx
  frontend/src/page/Signin/index.tsx
  frontend/src/page/Signup/index.tsx
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: 프론트엔드, 세팅

#18 라우팅 처리 및 배경 추가
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/assets/background.mp4
  frontend/src/component/Background/background.styled.ts
  frontend/src/component/Background/index.tsx
  frontend/src/component/Modal/index.tsx
  frontend/src/component/Modal/modal.styled.ts
  frontend/src/global.ts
  frontend/src/index.tsx
  frontend/src/page/Main/index.tsx
  frontend/src/page/Signin/index.tsx
  frontend/src/page/Signup/index.tsx
Labels: 프론트엔드, 세팅, 디자인

#20 Main page 마크업
  frontend/src/component/Button/button.styled.ts
  frontend/src/component/Button/index.tsx
  frontend/src/component/MainContent/index.tsx
  frontend/src/component/MainContent/mainContent.styled.ts
  frontend/src/page/Main/index.tsx
Labels: 프론트엔드, 디자인

#21 children type 분리 및 modal css 수정
  frontend/src/component/Background/index.tsx
  frontend/src/component/Modal/index.tsx
  frontend/src/component/Modal/modal.styled.ts
  frontend/src/page/Signup/index.tsx
  frontend/src/page/Signup/signup.styled.ts
  frontend/src/types/types.ts
Labels: 프론트엔드, 디자인

#23 소셜에 따른 로그인 페이지 redirection 제공
  backend/src/user/user.controller.ts
Labels: 백엔드, 기능

#24 Signin page 마크업
  frontend/src/assets/preview.gif
  frontend/src/component/Button/button.styled.ts
  frontend/src/component/Button/index.tsx
  frontend/src/component/MainContent/index.tsx
  frontend/src/component/MainContent/mainContent.styled.ts
  frontend/src/component/SigninContent/index.tsx
  frontend/src/component/SigninContent/signinContent.styled.ts
  frontend/src/page/Signin/index.tsx
Labels: 프론트엔드, 디자인

#25 [feat] #4 #5 카카오 소셜 로그인 구현 (1/2)
  backend/src/user/user.controller.ts
  backend/src/user/user.enum.ts
  backend/src/user/user.service.ts
Labels: 백엔드, 기능

#26 Signup page 개발
  frontend/src/assets/character/waiting/base_waiting_strip9.png
  frontend/src/assets/character/waiting/base_waiting_strip9.svg
  frontend/src/assets/character/waiting/bowlhair_waiting_strip9.png
  frontend/src/assets/character/waiting/curlyhair_waiting_strip9.png
  frontend/src/assets/character/waiting/longhair_waiting_strip9.png
  frontend/src/assets/character/waiting/mophair_waiting_strip9.png
  frontend/src/assets/character/waiting/shorthair_waiting_strip9.png
  frontend/src/assets/character/waiting/spikeyhair_waiting_strip9.png
  frontend/src/assets/character/waiting/tools_waiting_strip9.png
  frontend/src/assets/character/walking/base_walk_strip8.png
  frontend/src/assets/character/walking/bowlhair_walk_strip8.png
  frontend/src/assets/character/walking/curlyhair_walk_strip8.png
  frontend/src/assets/character/walking/longhair_walk_strip8.png
  frontend/src/assets/character/walking/mophair_walk_strip8.png
  frontend/src/assets/character/walking/shorthair_walk_strip8.png
  frontend/src/assets/character/walking/spikeyhair_walk_strip8.png
  frontend/src/assets/character/walking/tools_walk_strip8.png
  frontend/src/assets/nextArrow.svg
  frontend/src/assets/prevArrow.svg
  frontend/src/component/Button/button.styled.ts
  frontend/src/component/Button/index.tsx
  frontend/src/component/Setting/hair.ts
  frontend/src/component/Setting/index.tsx
  frontend/src/component/Setting/setting.styled.ts
  frontend/src/page/Signup/index.tsx
  frontend/src/page/Signup/signup.styled.ts
  frontend/src/styles/mixin.styled.ts
Labels: 프론트엔드, 디자인, 기능

#28 CORS 에러 해결
  backend/src/main.ts
Labels: 버그

#30 [feat] #4 #5 구글 로그인 구현 (1/2)
  backend/src/main.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
Labels: 백엔드, 기능

#32 Phaser config 생성, page 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Router.tsx
  frontend/src/component/Button/index.tsx
  frontend/src/component/Game/game.styled.ts
  frontend/src/component/Game/gameConfig.ts
  frontend/src/component/Game/index.tsx
  frontend/src/component/Setting/index.tsx
  frontend/src/global.ts
  frontend/src/index.tsx
  frontend/src/page/Town/index.tsx
Labels: 프론트엔드, 기능

#33 Phaser 배경 이미지 적용
  frontend/package-lock.json
  frontend/src/assets/background.png
  frontend/src/component/Game/game.ts
  frontend/src/component/Game/gameConfig.ts
Labels: 프론트엔드, 기능

#35 town page - 캐릭터 랜더링 및 이동
  frontend/src/assets/character/roll/base_roll_strip10.png
  frontend/src/assets/character/roll/bowlhair_roll_strip10.png
  frontend/src/assets/character/roll/curlyhair_roll_strip10.png
  frontend/src/assets/character/roll/longhair_roll_strip10.png
  frontend/src/assets/character/roll/mophair_roll_strip10.png
  frontend/src/assets/character/roll/shorthair_roll_strip10.png
  frontend/src/assets/character/roll/spikeyhair_roll_strip10.png
  frontend/src/assets/character/roll/tools_roll_strip10.png
  frontend/src/component/Game/game.ts
Labels: 프론트엔드, 기능

#38 로그인 기능 완벽 구현
  backend/README.md
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/entity/user.entity.ts
  backend/src/auth/jwt-auth.strategy.ts
  backend/src/auth/user.controller.ts
  backend/src/auth/user.enum.ts
  backend/src/auth/user.service.ts
  backend/src/main.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
Labels: 백엔드, 리팩토링, 기능, 문서

#39 player 로직 분리 및 key event 수정
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Game/util.ts
Labels: 프론트엔드, 리팩토링, 기능

#40 유저 시스템 완성 및 코드 퀄리티 향상
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/user-data.dto.ts
  backend/src/auth/entity/user.entity.ts
  backend/src/auth/jwt-auth.strategy.ts
  backend/src/auth/pipes/social-platform.pipe.ts
  backend/src/auth/user.controller.ts
  backend/src/auth/user.service.ts
Labels: 백엔드, 리팩토링, 기능

#41 게임 부가 기능 추가(배경음악, 눈내리기)
  frontend/src/assets/audio/christmas.mp3
  frontend/src/component/Game/game.ts
  frontend/src/component/Snow/index.tsx
  frontend/src/component/Snow/snow.styled.ts
  frontend/src/page/Town/index.tsx
Labels: 프론트엔드, 디자인, 기능

#54 phaser(canvas) 사이즈 버그 개선
  frontend/src/component/Game/gameConfig.ts
  frontend/src/global.ts
Labels: 프론트엔드, 버그

#55 구르기 및 눈 내리기 리팩토링
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Snow/index.tsx
  frontend/src/component/Snow/snow.styled.ts
Labels: 프론트엔드, 리팩토링

#56 [refactor] #4 #5 유저 관리 시스템 내부 로직 변경
  backend/package-lock.json
  backend/package.json
  backend/src/auth/dto/user-data.dto.ts
  backend/src/auth/jwt-auth.strategy.ts
  backend/src/auth/user.controller.ts
  backend/src/auth/user.service.ts
Labels: 백엔드, 버그, 리팩토링, 기능

#57 Authorization API 추가
  backend/src/auth/user.controller.ts
Labels: 백엔드, 기능

#58 sprite 이미지 통합
  frontend/src/assets/character/roll/base_roll_strip10.png
  frontend/src/assets/character/roll/bowlhair_roll_strip10.png
  frontend/src/assets/character/roll/curlyhair_roll_strip10.png
  frontend/src/assets/character/roll/longhair_roll_strip10.png
  frontend/src/assets/character/roll/mophair_roll_strip10.png
  frontend/src/assets/character/roll/roll.png
  frontend/src/assets/character/roll/shorthair_roll_strip10.png
  frontend/src/assets/character/roll/spikeyhair_roll_strip10.png
  frontend/src/assets/character/roll/tools_roll_strip10.png
  frontend/src/assets/character/run/run.png
  frontend/src/assets/character/sprite.json
  frontend/src/assets/character/waiting/base_waiting_strip9.png
  frontend/src/assets/character/waiting/base_waiting_strip9.svg
  frontend/src/assets/character/waiting/bowlhair_waiting_strip9.png
  frontend/src/assets/character/waiting/curlyhair_waiting_strip9.png
  frontend/src/assets/character/waiting/longhair_waiting_strip9.png
  frontend/src/assets/character/waiting/mophair_waiting_strip9.png
  frontend/src/assets/character/waiting/shorthair_waiting_strip9.png
  frontend/src/assets/character/waiting/spikeyhair_waiting_strip9.png
  frontend/src/assets/character/waiting/tools_waiting_strip9.png
  frontend/src/assets/character/waiting/wait.png
  frontend/src/assets/character/walking/base_walk_strip8.png
  frontend/src/assets/character/walking/bowlhair_walk_strip8.png
  frontend/src/assets/character/walking/curlyhair_walk_strip8.png
  frontend/src/assets/character/walking/longhair_walk_strip8.png
  frontend/src/assets/character/walking/mophair_walk_strip8.png
  frontend/src/assets/character/walking/shorthair_walk_strip8.png
  frontend/src/assets/character/walking/spikeyhair_walk_strip8.png
  frontend/src/assets/character/walking/tools_walk_strip8.png
  frontend/src/assets/character/walking/walk.png
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Setting/hair.ts
  frontend/src/component/Setting/index.tsx
  frontend/src/component/Setting/setting.styled.ts
Labels: 프론트엔드, 리팩토링, 기능

#59 로그인 및 회원가입 api 연결, proxy 세팅
  frontend/src/component/Button/index.tsx
  frontend/src/component/MainContent/index.tsx
  frontend/src/component/Setting/index.tsx
  frontend/src/page/Main/index.tsx
  frontend/vite.config.ts
Labels: 프론트엔드, 세팅, 기능

#60 달리기, 구르기 먼지 이펙트 추가
  frontend/src/assets/character/dust.png
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Game/util.ts
Labels: 프론트엔드, 기능

#61 sidebar 마크업
  frontend/src/assets/icon/cam-off.svg
  frontend/src/assets/icon/cam-on.svg
  frontend/src/assets/icon/chattingIcon.svg
  frontend/src/assets/icon/friendsListIcon.svg
  frontend/src/assets/icon/mic-off.svg
  frontend/src/assets/icon/mic-on.svg
  frontend/src/assets/icon/mypageIcon.svg
  frontend/src/assets/icon/settingIcon.svg
  frontend/src/assets/sidebar-close.svg
  frontend/src/assets/sidebar-open.svg
  frontend/src/component/Sidebar/index.tsx
  frontend/src/component/Sidebar/sidebar.styled.ts
  frontend/src/global.ts
  frontend/src/page/Town/index.tsx
Labels: 프론트엔드, 디자인, 기능

#63 sidebar - mypage 구현(1/2)
  frontend/src/component/Button/button.styled.ts
  frontend/src/component/Button/index.tsx
  frontend/src/component/Carousel/Calrousel.tsx
  frontend/src/component/Carousel/carousel.styled.ts
  frontend/src/component/Carousel/hair.ts
  frontend/src/component/Setting/index.tsx
  frontend/src/component/Setting/setting.styled.ts
  frontend/src/component/Sidebar/Content/content.styled.ts
  frontend/src/component/Sidebar/Content/index.tsx
  frontend/src/component/Sidebar/Mypage/index.tsx
  frontend/src/component/Sidebar/Mypage/mypage.styled.ts
  frontend/src/component/Sidebar/index.tsx
  frontend/src/component/Sidebar/sidebar.styled.ts
Labels: 프론트엔드, 디자인, 기능

#64 Sidebar - mypage
  frontend/src/component/Button/button.styled.ts
  frontend/src/component/Button/index.tsx
  frontend/src/component/Setting/index.tsx
  frontend/src/component/Sidebar/Mypage/CarouselContent.tsx
  frontend/src/component/Sidebar/Mypage/NickNameContent.tsx
  frontend/src/component/Sidebar/Mypage/index.tsx
Labels: 프론트엔드, 리팩토링, 기능

#62 태그 변경 및 마크업 수정
  frontend/src/component/Sidebar/index.tsx
  frontend/src/component/Sidebar/sidebar.styled.ts
Labels: 프론트엔드, 리팩토링

#65 sidebar 탭간 이동 구현
  frontend/src/component/Sidebar/index.tsx
Labels: 프론트엔드, 기능

#67 friend list 컴포넌트 마크업
  frontend/src/assets/icon/addFriendIcon.svg
  frontend/src/assets/icon/messageIcon.svg
  frontend/src/assets/icon/phoneIcon.svg
  frontend/src/assets/icon/unfollowIcon.svg
  frontend/src/component/Sidebar/Content/content.styled.ts
  frontend/src/component/Sidebar/Content/index.tsx
  frontend/src/component/Sidebar/Friends/callingList.tsx
  frontend/src/component/Sidebar/Friends/friendItem.tsx
  frontend/src/component/Sidebar/Friends/friendList.tsx
  frontend/src/component/Sidebar/Friends/friends.styled.ts
  frontend/src/component/Sidebar/Friends/friends.ts
  frontend/src/component/Sidebar/Friends/index.tsx
  frontend/src/component/Sidebar/Mypage/index.tsx
  frontend/src/component/Sidebar/Mypage/mypage.styled.ts
  frontend/src/component/Sidebar/index.tsx
Labels: 프론트엔드, 디자인, 리팩토링

#68 게시글 관련 일부 API 구현
  backend/src/app.module.ts
  backend/src/auth/entity/user.entity.ts
  backend/src/board/article.enum.ts
  backend/src/board/board.controller.ts
  backend/src/board/board.module.ts
  backend/src/board/board.service.ts
  backend/src/board/dto/article-data.dto.ts
  backend/src/board/entity/board-like.entity.ts
  backend/src/board/entity/board.entity.ts
Labels: 백엔드, 기능

#71 팔로우 기능 완성
  backend/src/app.module.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/entity/user.entity.ts
  backend/src/auth/user.service.ts
  backend/src/friendship/entity/follwing.entity.ts
  backend/src/friendship/friendship.controller.ts
  backend/src/friendship/friendship.module.ts
  backend/src/friendship/friendship.service.ts
Labels: 백엔드, 리팩토링, 기능

#72 캐릭터 이동 키보드 버그 수정
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/util.ts
  frontend/src/component/Sidebar/Mypage/mypage.styled.ts
Labels: 프론트엔드, 버그, 기능

#74 Chat component 구현
  frontend/src/component/Sidebar/Chat/chat.styled.ts
  frontend/src/component/Sidebar/Chat/chatData.ts
  frontend/src/component/Sidebar/Chat/chatItem.tsx
  frontend/src/component/Sidebar/Chat/index.tsx
  frontend/src/component/Sidebar/Content/content.styled.ts
  frontend/src/component/Sidebar/Content/index.tsx
  frontend/src/component/Sidebar/index.tsx
  frontend/src/component/Sidebar/sidebar.styled.ts
  frontend/src/styles/theme.ts
Labels: 프론트엔드, 디자인

#77 SleepyBoard 모달 구현
  frontend/src/assets/tree.svg
  frontend/src/assets/trophy.svg
  frontend/src/component/SleepyBoard/index.tsx
  frontend/src/component/SleepyBoard/sleepyboard.styled.ts
  frontend/src/page/Town/index.tsx
Labels: 프론트엔드, 디자인

#78 SleepyBoard 관련 API 생성 및 응답 구체화
  backend/src/auth/user.controller.ts
  backend/src/auth/user.service.ts
  backend/src/board/board.controller.ts
  backend/src/board/board.module.ts
  backend/src/board/board.service.ts
  backend/src/board/dto/article-data.dto.ts
  backend/src/board/entity/board.entity.ts
  backend/src/board/pipes/category.pipe.ts
  backend/src/friendship/friendship.controller.ts
  backend/src/friendship/friendship.service.ts
Labels: 백엔드, 리팩토링, 기능

#79 회원가입 에러처리
  frontend/src/component/Button/button.styled.ts
  frontend/src/component/Setting/index.tsx
  frontend/src/component/Setting/setting.styled.ts
  frontend/src/component/SleepyBoard/index.tsx
  frontend/src/component/SleepyBoard/sleepyboard.styled.ts
Labels: 프론트엔드, 디자인, 기능

#81 Player class 분리
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
  frontend/src/component/Game/Phaser/Player/otherPlayer.ts
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Game/util.ts
Labels: 프론트엔드, 리팩토링, 기능

#84 에러 해결 및 스타일 수정
  frontend/src/component/Game/game.ts
  frontend/src/component/Game/gameConfig.ts
  frontend/src/component/Sidebar/Friends/friends.styled.ts
Labels: 프론트엔드, 리팩토링

#86 recoil 설치 및 atom 생성
  frontend/package-lock.json
  frontend/package.json
  frontend/src/store/atom/backgroundSetting.ts
  frontend/src/store/atom/deviceSetting.ts
  frontend/src/store/atom/user.ts
  frontend/src/types/types.ts
Labels: 프론트엔드, 기능

#87 로딩페이지
  frontend/src/assets/run.gif
  frontend/src/component/Game/Phaser/Player/otherPlayer.ts
  frontend/src/component/Loading/index.tsx
  frontend/src/component/Loading/loading.styled.ts
  frontend/src/component/Sidebar/Chat/chatItem.tsx
  frontend/src/page/Town/index.tsx
Labels: 프론트엔드, 기능

#88 sleepyBoard content 마크업 및 스타일링
  frontend/src/assets/icon/like.svg
  frontend/src/assets/icon/unlike.svg
  frontend/src/component/SleepyBoard/boardData.ts
  frontend/src/component/SleepyBoard/content.tsx
  frontend/src/component/SleepyBoard/index.tsx
  frontend/src/component/SleepyBoard/sleepyboard.styled.ts
Labels: 프론트엔드, 디자인

#90 jump 추가
  frontend/src/assets/character/jump/jump.png
  frontend/src/assets/character/wait/wait.png
  frontend/src/assets/character/walk/walk.png
  frontend/src/component/Carousel/carousel.styled.ts
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
Labels: 프론트엔드, 리팩토링, 기능

#91 전역 상태 관리
  frontend/src/App.tsx
  frontend/src/component/Sidebar/Setting/backgroundSetting.tsx
  frontend/src/component/Sidebar/Setting/deviceSetting.tsx
  frontend/src/component/Sidebar/Setting/index.tsx
  frontend/src/component/Sidebar/index.tsx
  frontend/src/page/Main/index.tsx
  frontend/src/page/Town/index.tsx
  frontend/src/store/atom/user.ts
Labels: 프론트엔드, 기능

#92 Socket 연결 및 기본 동작 구현
  backend/package-lock.json
  backend/package.json
  backend/src/adapters/socket-io.adapter.ts
  backend/src/app.module.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/jwt-auth.strategy.ts
  backend/src/auth/pipes/characterName.pipe.ts
  backend/src/auth/user.controller.ts
  backend/src/main.ts
  backend/src/socket/dto/player.dto.ts
  backend/src/socket/enum/player.enum.ts
  backend/src/socket/filter/ws.filter.ts
  backend/src/socket/pipes/movement.pipe.ts
  backend/src/socket/socket.gateway.ts
  backend/src/socket/socket.module.ts
  backend/src/socket/socket.service.ts
Labels: 백엔드, 리팩토링, 기능

#94 Socket을 통한 채팅 구현 및 DB 리팩토링
  backend/src/auth/entity/user.entity.ts
  backend/src/board/entity/board-like.entity.ts
  backend/src/board/entity/board.entity.ts
  backend/src/friendship/entity/follwing.entity.ts
  backend/src/socket/socket.gateway.ts
Labels: 백엔드, 리팩토링, 기능

#95 frontend 소켓 연결
  backend/src/adapters/socket-io.adapter.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/component/Game/game.ts
  frontend/src/page/Main/index.tsx
  frontend/src/page/Town/index.tsx
  frontend/src/store/atom/socket.ts
Labels: 프론트엔드, 기능

#97 회원탈퇴, socket 전역
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/component/Button/button.styled.ts
  frontend/src/component/Button/index.tsx
  frontend/src/component/Carousel/hair.ts
  frontend/src/component/Sidebar/Mypage/CarouselContent.tsx
  frontend/src/component/Sidebar/Mypage/NickNameContent.tsx
  frontend/src/component/Sidebar/Mypage/index.tsx
  frontend/src/component/Sidebar/Mypage/mypage.styled.ts
  frontend/src/page/Main/index.tsx
  frontend/src/store/atom/socket.ts
Labels: 프론트엔드, 리팩토링, 기능

#98 Phaser 소켓 통신 - 캐릭터 입장
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
  frontend/src/component/Game/Phaser/Player/otherPlayer.ts
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Game/index.tsx
  frontend/src/component/Game/util.ts
Labels: 프론트엔드, 기능

#99 채팅방 생성, 채팅 기록, 열람내역 저장
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/entity/user.entity.ts
  backend/src/chat/chat.controller.ts
  backend/src/chat/chat.module.ts
  backend/src/chat/chat.service.ts
  backend/src/chat/entity/chat-mark.entity.ts
  backend/src/chat/entity/chat-room.entity.ts
  backend/src/chat/entity/chat.entity.ts
  backend/src/socket/socket.gateway.ts
Labels: 백엔드, 기능

#100 배경음악 설정
  frontend/src/component/Game/game.ts
  frontend/src/component/Sidebar/Setting/backgroundSetting.tsx
  frontend/src/store/atom/backgroundSetting.ts
Labels: 프론트엔드, 기능

#101 캐릭터 이동(socket), 눈내리기 버그 수정
  backend/package-lock.json
  backend/src/socket/enum/player.enum.ts
  backend/src/socket/socket.gateway.ts
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Game/util.ts
  frontend/src/component/Snow/snow.styled.ts
  frontend/src/page/Main/index.tsx
  frontend/src/page/Town/index.tsx
Labels: 백엔드, 프론트엔드, 버그, 기능

#102 채팅방 목록 및 채팅 내용 불러오기 API
  backend/src/chat/chat.controller.ts
  backend/src/chat/chat.service.ts
  backend/src/chat/entity/chat-mark.entity.ts
  backend/src/friendship/friendship.service.ts
  backend/src/socket/socket.gateway.ts
  frontend/package-lock.json
Labels: 백엔드, 리팩토링, 기능

#103 SleepyBoard 필터 버튼, 맵을 떠난 유저 삭제
  backend/src/socket/socket.gateway.ts
  frontend/src/assets/icon/user.svg
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/SleepyBoard/SleepyBoardContainer.tsx
  frontend/src/component/SleepyBoard/index.tsx
  frontend/src/component/SleepyBoard/sleepyboard.styled.ts
Labels: 프론트엔드, 디자인, 기능

#105 DB nickname, characterName 자료형 및 검증 로직 수정
  backend/src/auth/dto/user-data.dto.ts
  backend/src/auth/entity/user.entity.ts
  backend/src/chat/entity/chat.entity.ts
Labels: 백엔드, 프론트엔드, 버그, 리팩토링

#107 Socket 명세 구체화 및 Wiki 작성
  README.md
  backend/src/chat/chat.service.ts
  backend/src/socket/socket.gateway.ts
Labels: 백엔드, 버그, 디자인, 리팩토링, 문서

#109 nickname 표시, 버그수정, 마이페이지 로직
  frontend/src/Router.tsx
  frontend/src/assets/character/sprite.json
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Game/index.tsx
  frontend/src/component/Game/util.ts
  frontend/src/component/MainContent/index.tsx
  frontend/src/component/Setting/index.tsx
  frontend/src/component/Sidebar/Mypage/CarouselContent.tsx
  frontend/src/component/Sidebar/Mypage/NickNameContent.tsx
  frontend/src/component/Sidebar/Mypage/mypage.styled.ts
  frontend/src/page/Main/index.tsx
Labels: 프론트엔드, 버그, 리팩토링, 기능
