Repository boostcampwm-2022/web05-SleepyWoods, pull requests merged in 2022-12, with the labels that each got.

#115 게시글 조회 필터, 유저데이터 변경 broadcast
  backend/package-lock.json
  backend/src/board/board.controller.ts
  backend/src/board/board.service.ts
  backend/src/board/entity/board.entity.ts
  backend/src/socket/socket.gateway.ts
Labels: 백엔드, 기능

#113 유저가 떠났을때 닉네임 지워주기
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
Labels: 버그

#116 친구 추가 로직 구현
  frontend/src/Router.tsx
  frontend/src/component/Sidebar/Friends/callingList.tsx
  frontend/src/component/Sidebar/Friends/friendItem.tsx
  frontend/src/component/Sidebar/Friends/friendList.tsx
  frontend/src/component/Sidebar/Friends/friends.styled.ts
  frontend/src/component/Sidebar/Friends/friends.ts
  frontend/src/component/Sidebar/Friends/search.tsx
  frontend/src/page/Main/index.tsx
  frontend/src/store/atom/friends.ts
Labels: 프론트엔드, 기능

#117 전체 채팅 및 1:1 채팅
  frontend/src/assets/icon/downArrow.svg
  frontend/src/component/Chat/ChatContent.tsx
  frontend/src/component/Chat/chat.styled.ts
  frontend/src/component/Chat/index.tsx
  frontend/src/component/Sidebar/Chat/ChatList.tsx
  frontend/src/component/Sidebar/Chat/ChatMessage.tsx
  frontend/src/component/Sidebar/Chat/ChatRoom.tsx
  frontend/src/component/Sidebar/Chat/Chatting.tsx
  frontend/src/component/Sidebar/Chat/chat.styled.ts
  frontend/src/component/Sidebar/Chat/chatData.ts
  frontend/src/component/Sidebar/Chat/chatItem.tsx
  frontend/src/component/Sidebar/Chat/index.tsx
  frontend/src/component/Sidebar/Chat/util.ts
  frontend/src/component/Sidebar/Content/content.styled.ts
  frontend/src/component/Sidebar/Content/index.tsx
  frontend/src/page/Town/index.tsx
Labels: 프론트엔드, 디자인, 기능

#125 시작 닉네임으로 유저 목록 검색
  backend/package-lock.json
  backend/src/auth/user.service.ts
  backend/src/friendship/friendship.controller.ts
Labels: 백엔드, 기능

#128 채팅방목록, 친구 추가, 게시글목록 반환값 수정
  backend/src/board/board.service.ts
  backend/src/chat/chat.service.ts
  backend/src/friendship/friendship.controller.ts
  backend/src/friendship/friendship.service.ts
Labels: 백엔드, 기능

#127 frontend guard 설정 및 친구 목록 수정
  frontend/src/Router.tsx
  frontend/src/component/Sidebar/Friends/friendList.tsx
  frontend/src/component/Sidebar/Friends/friends.styled.ts
  frontend/src/guard.tsx
  frontend/src/page/Main/index.tsx
  frontend/src/page/Town/index.tsx
  frontend/src/store/atom/friends.ts
Labels: 프론트엔드, 리팩토링, 기능

#130 버그 수정 및 입퇴장, 로그아웃, 유저 정보 수정
  backend/src/auth/user.controller.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/logo.png
  frontend/src/component/Chat/ChatContent.tsx
  frontend/src/component/Chat/ChatMessage.tsx
  frontend/src/component/Chat/Input.tsx
  frontend/src/component/Chat/chat.styled.ts
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
  frontend/src/component/Game/Phaser/Player/otherPlayer.ts
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Sidebar/Mypage/CarouselContent.tsx
  frontend/src/component/Sidebar/Mypage/LogoutButton.tsx
  frontend/src/component/Sidebar/Mypage/NickNameContent.tsx
  frontend/src/component/Sidebar/Mypage/index.tsx
  frontend/src/component/Sidebar/Mypage/mypage.styled.ts
  frontend/src/component/Sidebar/index.tsx
  frontend/src/component/SleepyBoard/SleepyBoardContainer.tsx
  frontend/src/component/SleepyBoard/content.tsx
  frontend/src/component/SleepyBoard/util.ts
  frontend/src/store/atom/backgroundSetting.ts
  frontend/src/store/atom/deviceSetting.ts
  frontend/src/store/atom/friends.ts
  frontend/src/store/atom/socket.ts
  frontend/src/store/atom/user.ts
Labels: 프론트엔드, 버그, 디자인, 기능

#131 뒤로가기 후 재실행시 움직이지 않는 에러
  frontend/src/component/Game/index.tsx
Labels: 버그

#132 친구 추가 삭제 시, 전역 정보 반영 및 에러 수정
  frontend/src/component/Sidebar/Chat/ChatList.tsx
  frontend/src/component/Sidebar/Friends/callingList.tsx
  frontend/src/component/Sidebar/Friends/friendItem.tsx
  frontend/src/component/Sidebar/Friends/friendList.tsx
  frontend/src/component/Sidebar/Friends/friends.styled.ts
  frontend/src/component/Sidebar/Friends/friends.ts
  frontend/src/component/Sidebar/Friends/search.tsx
  frontend/src/component/Sidebar/index.tsx
  frontend/src/guard.tsx
  frontend/src/store/atom/backgroundSetting.ts
  frontend/src/store/atom/deviceSetting.ts
  frontend/src/store/atom/friends.ts
  frontend/src/store/atom/socket.ts
  frontend/src/store/atom/user.ts
Labels: 프론트엔드, 버그, 리팩토링, 기능

#133 채팅방 목록 배열 반환값 구체화
  backend/src/chat/chat.service.ts
  backend/src/chat/entity/chat-room.entity.ts
  backend/src/chat/entity/chat.entity.ts
Labels: 백엔드, 기능

#135 명예의 전당(걸음수 랭킹)
  frontend/src/component/SleepyBoard/RankContainer.tsx
  frontend/src/component/SleepyBoard/SleepyBoardContainer.tsx
  frontend/src/component/SleepyBoard/Tab.tsx
  frontend/src/component/SleepyBoard/boardData.ts
  frontend/src/component/SleepyBoard/index.tsx
  frontend/src/component/SleepyBoard/sleepyboard.styled.ts
  frontend/src/component/SleepyBoard/util.ts
Labels: 프론트엔드, 디자인, 기능

#144 걸음수 및 접속유저 표시 및 에러 수정
  frontend/src/assets/icon/users.svg
  frontend/src/assets/icon/walk.svg
  frontend/src/component/Chat/ChatMessage.tsx
  frontend/src/component/Chat/chat.styled.ts
  frontend/src/component/Chat/index.tsx
  frontend/src/component/Info/Users.tsx
  frontend/src/component/Info/Walk.tsx
  frontend/src/component/Info/index.tsx
  frontend/src/component/Info/info.styled.ts
  frontend/src/component/Sidebar/Chat/ChatMessage.tsx
  frontend/src/component/Sidebar/Chat/Chatting.tsx
  frontend/src/component/SleepyBoard/sleepyboard.styled.ts
  frontend/src/page/Town/index.tsx
Labels: 프론트엔드, 디자인, 기능

#145 카카오 소셜 로그인 문제 및 사소한 이슈 해결
  backend/src/auth/user.controller.ts
  backend/src/auth/user.service.ts
  backend/src/friendship/friendship.controller.ts
Labels: 백엔드, 버그

#149 친구 목록 메시지 보내기 연결
  frontend/src/component/Sidebar/Chat/index.tsx
  frontend/src/component/Sidebar/Friends/friendItem.tsx
  frontend/src/component/Sidebar/index.tsx
  frontend/src/component/Sidebar/sidebar.styled.ts
  frontend/src/store/atom/chatting.ts
  frontend/src/store/atom/sidebar.ts
Labels: 프론트엔드, 기능

#150 카카오 소셜 로그인 수정 및 유저 걸음 수 관리 및 저장
  backend/package-lock.json
  backend/package.json
  backend/src/achievement/achievement.controller.ts
  backend/src/achievement/achievement.module.ts
  backend/src/achievement/achievement.service.ts
  backend/src/achievement/entity/walk.entity.ts
  backend/src/app.module.ts
  backend/src/auth/entity/user.entity.ts
  backend/src/auth/user.controller.ts
  backend/src/socket/socket.gateway.ts
Labels: 백엔드, 버그, 리팩토링, 기능

#152 월별 걸음 수 랭킹 불러오기
  backend/src/achievement/achievement.controller.ts
  backend/src/achievement/achievement.module.ts
  backend/src/achievement/achievement.service.ts
  backend/src/achievement/entity/walk.entity.ts
Labels: 백엔드, 기능

#153 통화 연결 UI
  frontend/src/assets/icon/acceptCall.svg
  frontend/src/assets/icon/rejectCall.svg
  frontend/src/component/Call/call.styled.ts
  frontend/src/component/Call/callingItem.tsx
  frontend/src/component/Call/index.tsx
  frontend/src/component/Sidebar/Friends/callingList.tsx
  frontend/src/component/Sidebar/Friends/friendItem.tsx
  frontend/src/component/Sidebar/Friends/friends.ts
  frontend/src/component/Sidebar/Friends/search.tsx
  frontend/src/guard.tsx
  frontend/src/page/Town/index.tsx
  frontend/src/store/atom/friends.ts
  frontend/src/styles/theme.ts
Labels: 프론트엔드, 디자인, 기능

#154 1:1 채팅 구현 및 랭크 최근 3개월 마크업
  backend/src/chat/chat.service.ts
  frontend/src/component/Sidebar/Chat/ChatList.tsx
  frontend/src/component/Sidebar/Chat/ChatMessage.tsx
  frontend/src/component/Sidebar/Chat/ChatRoom.tsx
  frontend/src/component/Sidebar/Chat/Chatting.tsx
  frontend/src/component/Sidebar/Chat/chat.styled.ts
  frontend/src/component/Sidebar/Chat/index.tsx
  frontend/src/component/Sidebar/Chat/util.ts
  frontend/src/component/Sidebar/Content/index.tsx
  frontend/src/component/Sidebar/Friends/friendItem.tsx
  frontend/src/component/SleepyBoard/RankContainer.tsx
  frontend/src/component/SleepyBoard/SleepyBoardContainer.tsx
  frontend/src/component/SleepyBoard/index.tsx
  frontend/src/component/SleepyBoard/sleepyboard.styled.ts
  frontend/src/store/atom/chatting.ts
Labels: 프론트엔드, 디자인, 기능

#156 [fix] #155 정적 이미지 호출 방법 수정
  frontend/src/component/Background/index.tsx
  frontend/src/component/Game/game.ts
  frontend/src/component/Game/index.tsx
  frontend/src/component/MainContent/mainContent.styled.ts
  frontend/src/component/Oauth/index.tsx
  frontend/src/component/Oauth/oauth.styled.ts
  frontend/src/component/Sidebar/Friends/friendItem.tsx
  frontend/src/component/SigninContent/index.tsx
Labels: 프론트엔드, 버그

#157 걸음수
  frontend/src/component/Game/game.ts
  frontend/src/component/Info/Walk.tsx
  frontend/src/component/SleepyBoard/RankContainer.tsx
Labels: 프론트엔드, 기능

#158 채팅 메시지 없을 때 index error 수정
  frontend/src/component/Sidebar/Chat/Chatting.tsx
Labels: 프론트엔드, 버그

#159 .env 설정 및 경로 수정
  frontend/src/component/Button/index.tsx
  frontend/src/store/atom/socket.ts
  frontend/vite.config.ts
Labels: 프론트엔드, 기능

#163 충돌구현 (1/2)
  backend/package.json
  frontend/src/assets/tilemaps/town.json
  frontend/src/assets/tilemaps/town.png
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Game/util.ts
Labels: 프론트엔드, 기능

#166 페이저 움직임 수정 및 소켓 주소 변경
  backend/package-lock.json
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/util.ts
  frontend/src/store/atom/socket.ts
Labels: 프론트엔드, 리팩토링

#167 카카오계정 이슈, 소켓 유저상태 및 통화 상태관리, 배포 자동화
  .github/workflows/backend_deploy.yml
  .github/workflows/frontend_deploy.yml
  backend/src/auth/user.controller.ts
  backend/src/socket/socket.gateway.ts
Labels: 백엔드, 버그, 기능

#169 phaser refactoring
  frontend/src/component/Call/callingItem.tsx
  frontend/src/component/Call/index.tsx
  frontend/src/component/Game/game.ts
  frontend/src/component/Sidebar/Friends/friendItem.tsx
  frontend/src/component/Sidebar/Friends/friendList.tsx
  frontend/src/component/Sidebar/Friends/friends.styled.ts
  frontend/src/component/Sidebar/Friends/search.tsx
  frontend/src/global.ts
  frontend/src/guard.tsx
Labels: 프론트엔드, 버그, 리팩토링

#170 버그 수정 및 좋아요 토글
  backend/src/socket/socket.gateway.ts
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
  frontend/src/component/Game/Phaser/Player/otherPlayer.ts
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Game/util.ts
  frontend/src/component/SleepyBoard/content.tsx
  frontend/src/store/atom/socket.ts
Labels: 프론트엔드, 버그, 기능

#175 버그 수정 및 1:1 채팅 시간 출력
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Info/Walk.tsx
  frontend/src/component/Sidebar/Chat/ChatMessage.tsx
  frontend/src/component/Sidebar/Chat/ChatRoom.tsx
  frontend/src/component/Sidebar/Chat/Chatting.tsx
  frontend/src/component/Sidebar/Chat/SeparateTimeLine.tsx
  frontend/src/component/Sidebar/Chat/chat.styled.ts
  frontend/src/component/Sidebar/Chat/util.ts
  frontend/src/component/Sidebar/index.tsx
  frontend/src/component/SleepyBoard/RankContainer.tsx
  frontend/src/component/SleepyBoard/SleepyBoardContainer.tsx
  frontend/src/component/SleepyBoard/sleepyboard.styled.ts
Labels: 프론트엔드, 버그, 기능

#176 순간 이동 에러 수정
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
Labels: 프론트엔드, 버그

#178 통화 관련 socket 이벤트 완벽 구현, 좋아요한 게시글 조회 시 like 컬럼 추가
  backend/src/board/board.service.ts
  backend/src/socket/socket.gateway.ts
Labels: 백엔드, 프론트엔드, 기능

#181 도움말 및 공격모션 추가
  backend/src/socket/enum/player.enum.ts
  frontend/src/assets/character/attack/attack.png
  frontend/src/assets/character/sprite.json
  frontend/src/assets/character/tool/attack.png
  frontend/src/assets/icon/checkBox.svg
  frontend/src/assets/icon/close.svg
  frontend/src/assets/icon/help.svg
  frontend/src/assets/icon/keyboardA.svg
  frontend/src/assets/icon/keyboardArrow.svg
  frontend/src/assets/icon/keyboardR.svg
  frontend/src/assets/icon/keyboardShift.svg
  frontend/src/assets/icon/keyboardSpace.svg
  frontend/src/assets/info-boardAndRank.png
  frontend/src/assets/info-chat.png
  frontend/src/assets/info-friends.png
  frontend/src/assets/info-mypage.png
  frontend/src/assets/info-setting.png
  frontend/src/assets/info-walkAndUser.png
  frontend/src/assets/sidebarImg.png
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Game/util.ts
  frontend/src/component/Info/Help.tsx
  frontend/src/component/Info/HelpDescription/BoardAndRankInfo.tsx
  frontend/src/component/Info/HelpDescription/KeyBoardInfo.tsx
  frontend/src/component/Info/HelpDescription/SidebarInfo.tsx
  frontend/src/component/Info/HelpDescription/WalkAndUserInfo.tsx
  frontend/src/component/Info/HelpDescription/boardAndRankInfo.styled.ts
  frontend/src/component/Info/HelpDescription/common.styled.ts
  frontend/src/component/Info/HelpDescription/keyBoardInfo.styled.ts
  frontend/src/component/Info/HelpDescription/sidebarInfo.styled.ts
  frontend/src/component/Info/HelpDescription/walkAndUserInfo.styled.ts
  frontend/src/component/Info/index.tsx
  frontend/src/component/Info/info.styled.ts
  frontend/src/component/SleepyBoard/index.tsx
  frontend/src/component/SleepyBoard/sleepyboard.styled.ts
Labels: 프론트엔드, 디자인, 기능

#183 에러 수정 및 타입 추가
  frontend/src/component/Chat/ChatContent.tsx
  frontend/src/component/Chat/ChatMessage.tsx
  frontend/src/component/Chat/index.tsx
  frontend/src/component/Chat/util.ts
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
  frontend/src/component/Game/Phaser/Player/otherPlayer.ts
  frontend/src/component/Game/game.ts
  frontend/src/component/Game/util.ts
  frontend/src/component/Info/Help.tsx
  frontend/src/component/Info/Users.tsx
  frontend/src/component/Info/info.styled.ts
  frontend/src/component/Sidebar/Chat/ChatList.tsx
  frontend/src/component/Sidebar/Chat/ChatMessage.tsx
  frontend/src/component/Sidebar/Chat/ChatRoom.tsx
  frontend/src/component/Sidebar/Chat/Chatting.tsx
  frontend/src/component/Sidebar/Chat/util.ts
  frontend/src/component/SleepyBoard/RankContainer.tsx
  frontend/src/component/SleepyBoard/SleepyBoardContainer.tsx
  frontend/src/component/SleepyBoard/content.tsx
  frontend/src/component/SleepyBoard/sleepyboard.styled.ts
  frontend/src/component/SleepyBoard/util.ts
  frontend/src/page/Town/index.tsx
  frontend/src/store/atom/user.ts
  frontend/src/types/types.ts
Labels: 프론트엔드, 버그, 디자인, 기능

#186 scene 전환
  frontend/src/component/Game/Scene/game.ts
  frontend/src/component/Game/Scene/maze.ts
  frontend/src/component/Game/gameConfig.ts
Labels: 프론트엔드, 기능

#187 유저 상태 변경
  frontend/src/Router.tsx
  frontend/src/component/Call/callingItem.tsx
  frontend/src/component/Call/index.tsx
  frontend/src/component/Sidebar/Friends/callingList.tsx
  frontend/src/component/Sidebar/Friends/friendList.tsx
  frontend/src/guard.tsx
Labels: 프론트엔드, 리팩토링, 기능

#188 미니 게임 추가
  frontend/src/assets/character/attack/attack.png
  frontend/src/assets/character/jump/jump.png
  frontend/src/assets/character/roll/roll.png
  frontend/src/assets/character/run/run.png
  frontend/src/assets/character/sprite.json
  frontend/src/assets/character/swimming/swimming.png
  frontend/src/assets/character/tool/attack.png
  frontend/src/assets/character/walk/walk.png
  frontend/src/assets/tilemaps/maze/maze.json
  frontend/src/assets/tilemaps/maze/tileset3.png
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/Scene/maze.ts
  frontend/src/component/Game/Scene/onboard.ts
  frontend/src/component/Game/Scene/town.ts
  frontend/src/component/Game/gameConfig.ts
  frontend/src/component/Game/util.ts
Labels: 프론트엔드, 기능

#190 webRTC 1:1 화상 / 음성 채팅
  backend/src/socket/socket.gateway.ts
  frontend/src/component/Call/call.styled.ts
  frontend/src/component/Call/index.tsx
  frontend/src/component/Call/video.tsx
Labels: 백엔드, 프론트엔드, 기능

#192 유저 상태 로직 수정
  frontend/src/component/Call/index.tsx
  frontend/src/component/Sidebar/Friends/friendList.tsx
Labels: 프론트엔드, 리팩토링

#194 미니게임 모달
  frontend/src/component/Game/Scene/town.ts
  frontend/src/component/MiniGame/index.tsx
  frontend/src/component/MiniGame/miniGame.styled.ts
  frontend/src/page/Town/index.tsx
Labels: 프론트엔드, 디자인, 기능

#195 WebRTC를 통한 1:1 통화 기능 구현
  backend/src/app.module.ts
  backend/src/socket/socket.gateway.ts
  frontend/src/component/Call/call.styled.ts
  frontend/src/component/Call/callingItem.tsx
  frontend/src/component/Call/video.tsx
Labels: 백엔드, 프론트엔드, 세팅, 기능

#196 미니 게임
  frontend/src/assets/icon/check.svg
  frontend/src/assets/icon/copy.svg
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/MiniGame/FriendMode.tsx
  frontend/src/component/MiniGame/GameCode.tsx
  frontend/src/component/MiniGame/GameWait.tsx
  frontend/src/component/MiniGame/ModeBox.tsx
  frontend/src/component/MiniGame/index.tsx
  frontend/src/component/MiniGame/miniGame.styled.ts
Labels: 프론트엔드, 버그, 디자인, 기능

#197 술래잡기, 달리기 맵 추가
  frontend/src/assets/tilemaps/sprint/sprint.json
  frontend/src/assets/tilemaps/tile/tileset3.png
  frontend/src/assets/tilemaps/zombie/zombie.json
  frontend/src/component/Game/Scene/onboard.ts
  frontend/src/component/Game/Scene/sprint.ts
  frontend/src/component/Game/Scene/town.ts
  frontend/src/component/Game/Scene/zombie.ts
  frontend/src/component/Game/gameConfig.ts
  frontend/src/component/MiniGame/GameWait.tsx
  frontend/src/component/MiniGame/index.tsx
Labels: 프론트엔드, 기능

#198 [feat] #189 반쪽짜리 N:M WebRTC 구현
  frontend/src/component/Call/callingItem.tsx
  frontend/src/component/Call/config.ts
  frontend/src/component/Call/remoteVideo.tsx
  frontend/src/component/Call/video.tsx
  frontend/src/component/Call/vvv.tsx
  frontend/src/component/Game/Scene/sprint.ts
  frontend/src/component/Sidebar/Friends/callingList.tsx
  frontend/src/store/atom/callingList.ts
Labels: 백엔드, 프론트엔드, 세팅, 기능

#201 게임페이지에서 town으로 돌아가는 포탈 생성 및 버그 수정
  frontend/index.html
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
  frontend/src/component/Game/Scene/maze.ts
  frontend/src/component/Game/Scene/sprint.ts
  frontend/src/component/Game/Scene/town.ts
  frontend/src/component/Game/Scene/zombie.ts
  frontend/src/component/MiniGame/index.tsx
  frontend/src/component/Sidebar/index.tsx
  frontend/src/component/SleepyBoard/index.tsx
  frontend/src/page/Town/index.tsx
Labels: 프론트엔드, 버그, 기능

#202 webRTC 연결 시, 실시간 상태 변경
  frontend/src/component/Call/call.styled.ts
  frontend/src/component/Call/callingItem.tsx
  frontend/src/component/Call/index.tsx
  frontend/src/component/Call/video.tsx
  frontend/src/component/MiniGame/miniGame.styled.ts
  frontend/src/component/Sidebar/Friends/callingList.tsx
  frontend/src/component/Sidebar/Friends/friendList.tsx
Labels: 프론트엔드, 디자인, 리팩토링, 기능

#203 소켓 removeListener 버그 수정
  frontend/src/component/Call/call.styled.ts
  frontend/src/component/Call/remoteVideo.tsx
  frontend/src/component/Call/video.tsx
  frontend/src/component/Chat/ChatMessage.tsx
  frontend/src/component/Game/Phaser/Player/myPlayer.ts
  frontend/src/component/Game/Scene/town.ts
  frontend/src/component/Info/Users.tsx
  frontend/src/component/Info/Walk.tsx
  frontend/src/component/Sidebar/Chat/ChatList.tsx
  frontend/src/component/Sidebar/Chat/Chatting.tsx
  frontend/src/component/Sidebar/Friends/callingList.tsx
  frontend/src/component/Sidebar/Friends/friendList.tsx
Labels: 프론트엔드, 버그

#204 WebRTC 를 통한 N:M 화상 통화
  backend/src/board/article.enum.ts
  backend/src/socket/socket.gateway.ts
  frontend/src/component/Call/callingItem.tsx
  frontend/src/component/Call/index.tsx
  frontend/src/component/Call/remoteVideo.tsx
  frontend/src/component/Call/video.tsx
  frontend/src/component/Call/vvv.tsx
  frontend/src/component/Sidebar/Friends/callingList.tsx
Labels: 백엔드, 프론트엔드, 리팩토링

#205 [feat] #189 WebRTC를 통한 화상, 음성 통화 기능 완벽 구현
  backend/src/board/article.enum.ts
  backend/src/socket/socket.gateway.ts
  frontend/src/component/Call/call.styled.ts
  frontend/src/component/Call/callingItem.tsx
  frontend/src/component/Call/index.tsx
  frontend/src/component/Call/remoteVideo.tsx
  frontend/src/component/Call/video.tsx
  frontend/src/component/MiniGame/FriendMode.tsx
  frontend/src/component/Sidebar/Friends/callingList.tsx
  frontend/src/component/Sidebar/Friends/friendList.tsx
  frontend/src/component/Sidebar/index.tsx
  frontend/src/store/atom/deviceSetting.ts
  frontend/src/types/types.ts
Labels: 백엔드, 프론트엔드, 디자인, 기능

#206 미니게임 요소를 위한 작업
  backend/src/socket/socket.gateway.ts
  frontend/src/assets/tilemaps/running/running.json
  frontend/src/assets/tilemaps/survival/survival.json
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/Scene/onboard.ts
  frontend/src/component/Game/Scene/running.ts
  frontend/src/component/Game/Scene/survival.ts
  frontend/src/component/Game/Scene/town.ts
  frontend/src/component/Game/gameConfig.ts
  frontend/src/component/MiniGame/FriendMode.tsx
  frontend/src/component/MiniGame/GameWait.tsx
  frontend/src/component/MiniGame/index.tsx
Labels: 백엔드, 프론트엔드, 기능

#208 대규모 미니 게임 구현 및 버그 수정 및 리팩토링
  backend/package.json
  backend/src/auth/auth.service.ts
  backend/src/board/dto/article-data.dto.ts
  backend/src/board/entity/board.entity.ts
  backend/src/board/pipes/category.pipe.ts
  backend/src/socket/dto/player.dto.ts
  backend/src/socket/enum/player.enum.ts
  backend/src/socket/socket.gateway.ts
  backend/src/socket/socket.type.ts
  frontend/src/assets/finishline.png
  frontend/src/assets/flag.png
  frontend/src/component/Game/Phaser/Player/player.ts
  frontend/src/component/Game/Scene/maze.ts
  frontend/src/component/Game/Scene/onboard.ts
  frontend/src/component/Game/Scene/running.ts
  frontend/src/component/Game/Scene/town.ts
  frontend/src/component/Info/Walk.tsx
  frontend/src/component/MiniGame/GameResult.tsx
  frontend/src/component/MiniGame/GameWait.tsx
  frontend/src/component/MiniGame/index.tsx
  frontend/src/component/MiniGame/miniGame.styled.ts
  frontend/src/component/Sidebar/Content/content.styled.ts
  frontend/src/component/Sidebar/Friends/search.tsx
  frontend/src/component/SleepyBoard/content.tsx
Labels: 백엔드, 프론트엔드, 버그, 디자인, 리팩토링, 기능

#209 미니게임 에러 수정
  frontend/src/component/Game/Scene/maze.ts
  frontend/src/component/Game/Scene/running.ts
  frontend/src/component/Sidebar/sidebar.styled.ts
Labels: 버그

#211 버그 수정
  backend/src/socket/enum/player.enum.ts
  frontend/src/component/Game/Scene/maze.ts
  frontend/src/component/Game/Scene/running.ts
  frontend/src/component/Game/Scene/town.ts
  frontend/src/component/Info/Walk.tsx
  frontend/src/component/MiniGame/GameResult.tsx
  frontend/src/component/MiniGame/GameWait.tsx
  frontend/src/component/Sidebar/Friends/search.tsx
Labels: 프론트엔드, 버그, 기능

#212 SleepyWoods v1.0.7 배포
  backend/src/socket/enum/player.enum.ts
  frontend/src/component/Game/Scene/maze.ts
  frontend/src/component/Game/Scene/running.ts
  frontend/src/component/Game/Scene/town.ts
  frontend/src/component/Info/Walk.tsx
  frontend/src/component/MiniGame/GameResult.tsx
  frontend/src/component/MiniGame/GameWait.tsx
  frontend/src/component/Sidebar/Friends/search.tsx
Labels: 백엔드, 프론트엔드, 기능

#214 css 리팩토링 및 게시글 이미지 수정
  frontend/src/assets/maze.png
  frontend/src/assets/running.png
  frontend/src/component/Call/call.styled.ts
  frontend/src/component/Carousel/carousel.styled.ts
  frontend/src/component/Chat/chat.styled.ts
  frontend/src/component/Game/Scene/maze.ts
  frontend/src/component/Info/info.styled.ts
  frontend/src/component/Loading/loading.styled.ts
  frontend/src/component/MainContent/mainContent.styled.ts
  frontend/src/component/MiniGame/GameResult.tsx
  frontend/src/component/MiniGame/miniGame.styled.ts
  frontend/src/component/Sidebar/Chat/ChatList.tsx
  frontend/src/component/Sidebar/Chat/chat.styled.ts
  frontend/src/component/Sidebar/sidebar.styled.ts
  frontend/src/component/SigninContent/signinContent.styled.ts
  frontend/src/component/SleepyBoard/content.tsx
  frontend/src/component/SleepyBoard/sleepyboard.styled.ts
Labels: 프론트엔드, 리팩토링, 기능

#215 전체 채팅 스토리지 데이터 가져오기
  frontend/src/component/Chat/ChatMessage.tsx
Labels: 프론트엔드, 버그

#216 SleepyWoods v1.0.7 배포
  frontend/src/assets/maze.png
  frontend/src/assets/running.png
  frontend/src/component/Call/call.styled.ts
  frontend/src/component/Carousel/carousel.styled.ts
  frontend/src/component/Chat/ChatMessage.tsx
  frontend/src/component/Chat/chat.styled.ts
  frontend/src/component/Game/Scene/maze.ts
  frontend/src/component/Info/info.styled.ts
  frontend/src/component/Loading/loading.styled.ts
  frontend/src/component/MainContent/mainContent.styled.ts
  frontend/src/component/MiniGame/GameResult.tsx
  frontend/src/component/MiniGame/miniGame.styled.ts
  frontend/src/component/Sidebar/Chat/ChatList.tsx
  frontend/src/component/Sidebar/Chat/chat.styled.ts
  frontend/src/component/Sidebar/sidebar.styled.ts
  frontend/src/component/SigninContent/signinContent.styled.ts
  frontend/src/component/SleepyBoard/content.tsx
  frontend/src/component/SleepyBoard/sleepyboard.styled.ts
Labels: 프론트엔드, 버그, 리팩토링, 기능

#217 og 설정
  frontend/index.html
  frontend/src/assets/main.png
Labels: 기능
